#-------------------------------
# General Site Settings

title: Alys Murray - Romance with Heart 
logo: logo.png


menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Books and Movies, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: UA-165424514-1


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: alysmurray   # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Alys Murray <br> Romance Author

social:
- {icon: "ti-twitter", link: "https://twitter.com/writeralys"}
- {icon: "ti-facebook", link: "https://www.facebook.com/alysmurrayauthor/"}
- {icon: "ti-instagram", link: "https://www.instagram.com/writeralys/"}
- {icon: "ti-youtube", link: "https://www.youtube.com/channel/UCEFlLCbgJJJSkyCoKrci_FA"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Alys Murray is a screenwriter and author from New Orleans, Louisiana. With an original Christmas film on Lifetime and books published by Hallmark, Bookouture, and Entangled, she’s written something for the romantic in all of us!

blurb-btn-link: '/about'
blurb-btn-name: learn more



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section

portfolio-home-book-items:

  - image : "assets/images/portfolio/wildflower-promises.jpg"
    url: "/books/wildflower-promises/"

  - image : "assets/images/portfolio/sweet_pea.jpg"
    url: "/books/sweet-pea-summer"

  - image : "assets/images/portfolio/magnolia_sisters.jpg"
    url: "/books/the-magnolia-sisters"

  - image : "assets/images/portfolio/christmas_company.jpg"
    url: "/books/the-christmas-company"

  - image : "assets/images/portfolio/society_girl.jpg"
    url: "/books/society-girl/"

  - image : "assets/images/portfolio/love_spells.jpg"
    url: "/books/love-spells-for-the-end-of-the-world/"
    
  - image : "assets/images/portfolio/tea_cowboy.jpg"
    url: "/books/tea-and-a-cowboy/"


    
---
    


portfolio-home-movie-items:

  - image : "assets/images/portfolio/christmas_louisiana.jpg"
    url: "/movies/christmas-in-louisiana"


# Portfolio Page
portfolio-label:
- {
    title : "Novels",
    type : "novels"
  }
- {
    title : "Movies",
    type : "movies"
  }

portfolio-items:
  - image : "assets/images/portfolio/villain_lover.jpg"
    url: "/books/villain-lover/"
    portfolio-type:
     - type: "novels"

  - image : "assets/images/portfolio/wildflower-promises.jpg"
    url: "/books/wildflower-promises/"
    portfolio-type:
     - type: "novels"

  - image : "assets/images/portfolio/sweet_pea.jpg"
    url: "/books/sweet-pea-summer"
    portfolio-type:
     - type: "novels"

  - image : "assets/images/portfolio/magnolia_sisters.jpg"
    url: "/books/the-magnolia-sisters"
    portfolio-type:
     - type: "novels"

  - image : "assets/images/portfolio/christmas_company.jpg"
    url: "/books/the-christmas-company"
    portfolio-type:
     - type: "novels"

  - image : "assets/images/portfolio/society_girl.jpg"
    url: "/books/society-girl/"
    portfolio-type:
     - type: "novels"

  - image : "assets/images/portfolio/love_spells.jpg"
    url: "/books/love-spells-for-the-end-of-the-world/"
    portfolio-type:
     - type: "novels"
    
  - image : "assets/images/portfolio/tea_cowboy.jpg"
    url: "/books/tea-and-a-cowboy/"
    portfolio-type:
     - type: "novels"
     

  - image : "assets/images/portfolio/christmas_louisiana.jpg"
    url: "/movies/christmas-in-louisiana"
    portfolio-type:
     - type: "movies"
     
#-------------------------------
# Contact Section

contact-title: Contact
contact-email: alys.murray.13@gmail.com
